defineUniqueCities = () => {
  return [
    {
      IataCode: "ABJ",
      city: "Abidjan",
      country: "Ivory Coast",
      SkyscannerCode: "ABJ",
    },
    {
      IataCode: "ABV",
      city: "Abuja",
      country: "Nigeria",
      SkyscannerCode: "ABV",
    },
    { IataCode: "ACC", city: "Accra", country: "Ghana", SkyscannerCode: "ACC" },
    {
      IataCode: "ADD",
      city: "Addis Ababa",
      country: "Ethiopia",
      SkyscannerCode: "ADD",
    },
    {
      IataCode: "AKL",
      city: "Auckland",
      country: "New Zealand",
      SkyscannerCode: "AKL",
    },
    {
      IataCode: "ALG",
      city: "Algiers",
      country: "Algeria",
      SkyscannerCode: "ALG",
    },
    {
      IataCode: "AMM",
      city: "Amman",
      country: "Jordan",
      SkyscannerCode: "AMM",
    },
    {
      IataCode: "ANU",
      city: "Saint John’s",
      country: "Antigua and Barbuda",
      SkyscannerCode: "ANU",
    },
    {
      IataCode: "AUH",
      city: "Abu Dhabi",
      country: "United Arab Emirates",
      SkyscannerCode: "AUH",
    },
    {
      IataCode: "BAH",
      city: "Manama",
      country: "Bahrain",
      SkyscannerCode: "BAH",
    },
    {
      IataCode: "BCN",
      city: "Barcelona",
      country: "Spain",
      SkyscannerCode: "BCN",
    },
    {
      IataCode: "BDA",
      city: "Hamilton",
      country: "Bermuda",
      SkyscannerCode: "BDA",
    },
    {
      IataCode: "BEG",
      city: "Belgrade",
      country: "Serbia",
      SkyscannerCode: "BEG",
    },
    {
      IataCode: "BEY",
      city: "Beirut",
      country: "Lebanon",
      SkyscannerCode: "BEY",
    },
    {
      IataCode: "BGI",
      city: "Bridgetown",
      country: "Barbados",
      SkyscannerCode: "BGI",
    },
    {
      IataCode: "BJL",
      city: "Banjul",
      country: "Gambia",
      SkyscannerCode: "BJL",
    },
    {
      IataCode: "BKK",
      city: "Bangkok",
      country: "Thailand",
      SkyscannerCode: "BKK",
    },
    {
      IataCode: "BLZ",
      city: "Blantyre",
      country: "Malawi",
      SkyscannerCode: "BLZ",
    },
    {
      IataCode: "BOM",
      city: "Mumbai",
      country: "India",
      SkyscannerCode: "BOM",
    },
    {
      IataCode: "BRU",
      city: "Brussels",
      country: "Belgium",
      SkyscannerCode: "BRU",
    },
    {
      IataCode: "BTS",
      city: "Bratislava",
      country: "Slovakia",
      SkyscannerCode: "BTS",
    },
    {
      IataCode: "BUD",
      city: "Budapest",
      country: "Hungary",
      SkyscannerCode: "BUD",
    },
    {
      IataCode: "BWN",
      city: "Bandar Seri Begawan",
      country: "Brunei",
      SkyscannerCode: "BWN",
    },
    {
      IataCode: "CFU",
      city: "Corfu",
      country: "Greece",
      SkyscannerCode: "CFU",
    },
    {
      IataCode: "CGN",
      city: "Cologne",
      country: "Germany",
      SkyscannerCode: "CGN",
    },
    {
      IataCode: "CLJ",
      city: "Cluj Napoca",
      country: "Romania",
      SkyscannerCode: "CLJ",
    },
    {
      IataCode: "CLO",
      city: "Cali",
      country: "Colombia",
      SkyscannerCode: "CLO",
    },
    {
      IataCode: "CMB",
      city: "Colombo",
      country: "Sri Lanka",
      SkyscannerCode: "CMB",
    },
    {
      IataCode: "CMN",
      city: "Casablanca",
      country: "Morocco",
      SkyscannerCode: "CMN",
    },
    {
      IataCode: "COO",
      city: "Cotonou",
      country: "Benin",
      SkyscannerCode: "COO",
    },
    {
      IataCode: "CPH",
      city: "Copenhagen",
      country: "Denmark",
      SkyscannerCode: "CPH",
    },
    {
      IataCode: "CTU",
      city: "Chengdu",
      country: "China",
      SkyscannerCode: "CTU",
    },
    {
      IataCode: "DAC",
      city: "Dhaka",
      country: "Bangladesh",
      SkyscannerCode: "DAC",
    },
    {
      IataCode: "DAR",
      city: "Dar Es Salaam",
      country: "Tanzania",
      SkyscannerCode: "DAR",
    },
    {
      IataCode: "DLA",
      city: "Douala",
      country: "Cameroon",
      SkyscannerCode: "DLA",
    },
    {
      IataCode: "DLM",
      city: "Dalaman",
      country: "Turkey",
      SkyscannerCode: "DLM",
    },
    { IataCode: "DOH", city: "Doha", country: "Qatar", SkyscannerCode: "DOH" },
    {
      IataCode: "DOM",
      city: "Dominica",
      country: "Dominica",
      SkyscannerCode: "DOM",
    },
    {
      IataCode: "DSS",
      city: "Dakar",
      country: "Senegal",
      SkyscannerCode: "DSS",
    },
    {
      IataCode: "DUB",
      city: "Dublin",
      country: "Ireland",
      SkyscannerCode: "DUB",
    },
    {
      IataCode: "EBB",
      city: "Entebbe",
      country: "Uganda",
      SkyscannerCode: "EBB",
    },
    { IataCode: "EBL", city: "Erbil", country: "Iraq", SkyscannerCode: "EBL" },
    {
      IataCode: "EDI",
      city: "Edinburgh",
      country: "United Kingdom",
      SkyscannerCode: "EDI",
    },
    {
      IataCode: "EIN",
      city: "Eindhoven",
      country: "Netherlands",
      SkyscannerCode: "EIN",
    },
    {
      IataCode: "EVN",
      city: "Yerevan",
      country: "Armenia",
      SkyscannerCode: "EVN",
    },
    {
      IataCode: "EWR",
      city: "New York",
      country: "United States",
      SkyscannerCode: "EWR",
    },
    {
      IataCode: "EZE",
      city: "Buenos Aires",
      country: "Argentina",
      SkyscannerCode: "EZE",
    },
    {
      IataCode: "FAE",
      city: "Sorvagur",
      country: "Faroe Islands",
      SkyscannerCode: "FAE",
    },
    {
      IataCode: "FIH",
      city: "Kinshasa",
      country: "DR Congo",
      SkyscannerCode: "FIH",
    },
    {
      IataCode: "FNA",
      city: "Freetown",
      country: "Sierra Leone",
      SkyscannerCode: "FNA",
    },
    {
      IataCode: "FRU",
      city: "Bishkek",
      country: "Kyrgyzstan",
      SkyscannerCode: "FRU",
    },
    {
      IataCode: "GCI",
      city: "Guernsey",
      country: "Guernsey",
      SkyscannerCode: "GCI",
    },
    {
      IataCode: "GIB",
      city: "Gibraltar",
      country: "Gibraltar",
      SkyscannerCode: "GIB",
    },
    {
      IataCode: "GND",
      city: "St. George",
      country: "Grenada",
      SkyscannerCode: "GND",
    },
    {
      IataCode: "GOH",
      city: "Nuuk",
      country: "Greenland",
      SkyscannerCode: "GOH",
    },
    {
      IataCode: "GOT",
      city: "Gothenburg",
      country: "Sweden",
      SkyscannerCode: "GOT",
    },
    {
      IataCode: "GRU",
      city: "Sao Paulo",
      country: "Brazil",
      SkyscannerCode: "GRU",
    },
    {
      IataCode: "GUA",
      city: "Guatemala City",
      country: "Guatemala",
      SkyscannerCode: "GUA",
    },
    {
      IataCode: "GVA",
      city: "Geneva",
      country: "Switzerland",
      SkyscannerCode: "GVA",
    },
    {
      IataCode: "GYD",
      city: "Baku",
      country: "Azerbaijan",
      SkyscannerCode: "GYD",
    },
    {
      IataCode: "HAH",
      city: "Moroni",
      country: "Comoros",
      SkyscannerCode: "HAH",
    },
    {
      IataCode: "HAN",
      city: "Hanoi",
      country: "Vietnam",
      SkyscannerCode: "HAN",
    },
    {
      IataCode: "HEL",
      city: "Helsinki",
      country: "Finland",
      SkyscannerCode: "HEL",
    },
    {
      IataCode: "HGA",
      city: "Hargeisa",
      country: "Somalia",
      SkyscannerCode: "HGA",
    },
    {
      IataCode: "HKG",
      city: "Hong Kong",
      country: "Hong Kong",
      SkyscannerCode: "HKG",
    },
    {
      IataCode: "HRE",
      city: "Harare",
      country: "Zimbabwe",
      SkyscannerCode: "HRE",
    },
    {
      IataCode: "ICN",
      city: "Seoul",
      country: "South Korea",
      SkyscannerCode: "ICN",
    },
    {
      IataCode: "IEV",
      city: "Kyiv",
      country: "Ukraine",
      SkyscannerCode: "IEV",
    },
    { IataCode: "IKA", city: "Tehran", country: "Iran", SkyscannerCode: "IKA" },
    {
      IataCode: "JED",
      city: "Jeddah",
      country: "Saudi Arabia",
      SkyscannerCode: "JED",
    },
    {
      IataCode: "JIB",
      city: "Djibouti",
      country: "Djibouti",
      SkyscannerCode: "JIB",
    },
    {
      IataCode: "JNB",
      city: "Johannesburg",
      country: "South Africa",
      SkyscannerCode: "JNB",
    },
    {
      IataCode: "KBL",
      city: "Kabul",
      country: "Afghanistan",
      SkyscannerCode: "KBL",
    },
    {
      IataCode: "KEF",
      city: "Reykjavik",
      country: "Iceland",
      SkyscannerCode: "KEF",
    },
    {
      IataCode: "KGL",
      city: "Kigali",
      country: "Rwanda",
      SkyscannerCode: "KGL",
    },
    {
      IataCode: "KHI",
      city: "Karachi",
      country: "Pakistan",
      SkyscannerCode: "KHI",
    },
    {
      IataCode: "KIN",
      city: "Kingston",
      country: "Jamaica",
      SkyscannerCode: "KIN",
    },
    {
      IataCode: "KIV",
      city: "Chisinau",
      country: "Moldova",
      SkyscannerCode: "KIV",
    },
    {
      IataCode: "KNO",
      city: "Medan",
      country: "Indonesia",
      SkyscannerCode: "KNO",
    },
    {
      IataCode: "KRK",
      city: "Krakow",
      country: "Poland",
      SkyscannerCode: "KRK",
    },
    {
      IataCode: "KRT",
      city: "Khartoum",
      country: "Sudan",
      SkyscannerCode: "KRT",
    },
    {
      IataCode: "KTM",
      city: "Kathmandu",
      country: "Nepal",
      SkyscannerCode: "KTM",
    },
    {
      IataCode: "KUL",
      city: "Kuala Lumpur",
      country: "Malaysia",
      SkyscannerCode: "KUL",
    },
    {
      IataCode: "KWI",
      city: "Kuwait",
      country: "Kuwait",
      SkyscannerCode: "KWI",
    },
    {
      IataCode: "LBV",
      city: "Libreville",
      country: "Gabon",
      SkyscannerCode: "LBV",
    },
    { IataCode: "LFW", city: "Lome", country: "Togo", SkyscannerCode: "LFW" },
    { IataCode: "LIM", city: "Lima", country: "Peru", SkyscannerCode: "LIM" },
    {
      IataCode: "LIS",
      city: "Lisbon",
      country: "Portugal",
      SkyscannerCode: "LIS",
    },
    {
      IataCode: "LJU",
      city: "Ljubljana",
      country: "Slovenia",
      SkyscannerCode: "LJU",
    },
    {
      IataCode: "LUX",
      city: "Luxembourg",
      country: "Luxembourg",
      SkyscannerCode: "LUX",
    },
    { IataCode: "MCT", city: "Muscat", country: "Oman", SkyscannerCode: "MCT" },
    {
      IataCode: "MEX",
      city: "Mexico City",
      country: "Mexico",
      SkyscannerCode: "MEX",
    },
    { IataCode: "MFM", city: "Macau", country: "Macau", SkyscannerCode: "MFM" },
    { IataCode: "MLA", city: "Luqa", country: "Malta", SkyscannerCode: "MLA" },
    {
      IataCode: "MLE",
      city: "Malé",
      country: "Maldives",
      SkyscannerCode: "MLE",
    },
    {
      IataCode: "MNL",
      city: "Manila",
      country: "Philippines",
      SkyscannerCode: "MNL",
    },
    {
      IataCode: "MPM",
      city: "Maputo",
      country: "Mozambique",
      SkyscannerCode: "MPM",
    },
    {
      IataCode: "MRU",
      city: "Mauritius",
      country: "Mauritius",
      SkyscannerCode: "MRU",
    },
    {
      IataCode: "MSQ",
      city: "Minsk",
      country: "Belarus",
      SkyscannerCode: "MSQ",
    },
    {
      IataCode: "MVD",
      city: "Montevideo",
      country: "Uruguay",
      SkyscannerCode: "MVD",
    },
    { IataCode: "MXP", city: "Milan", country: "Italy", SkyscannerCode: "MXP" },
    {
      IataCode: "NBO",
      city: "Nairobi",
      country: "Kenya",
      SkyscannerCode: "NBO",
    },
    {
      IataCode: "NQZ",
      city: "Nur Sultan",
      country: "Kazakhstan",
      SkyscannerCode: "NQZ",
    },
    { IataCode: "NRT", city: "Tokyo", country: "Japan", SkyscannerCode: "NRT" },
    {
      IataCode: "OHD",
      city: "Ohrid",
      country: "North Macedonia",
      SkyscannerCode: "OHD",
    },
    {
      IataCode: "OUA",
      city: "Ouagadougou",
      country: "Burkina Faso",
      SkyscannerCode: "OUA",
    },
    {
      IataCode: "PER",
      city: "Perth",
      country: "Australia",
      SkyscannerCode: "PER",
    },
    {
      IataCode: "PFO",
      city: "Paphos",
      country: "Cyprus",
      SkyscannerCode: "PFO",
    },
    {
      IataCode: "PLS",
      city: "Providenciales",
      country: "Turks and Caicos Islands",
      SkyscannerCode: "PLS",
    },
    {
      IataCode: "PNH",
      city: "Phnom Penh",
      country: "Cambodia",
      SkyscannerCode: "PNH",
    },
    {
      IataCode: "POS",
      city: "Port Of Spain",
      country: "Trinidad and Tobago",
      SkyscannerCode: "POS",
    },
    {
      IataCode: "PPT",
      city: "Papeete",
      country: "French Polynesia",
      SkyscannerCode: "PPT",
    },
    {
      IataCode: "PRG",
      city: "Prague",
      country: "Czechia",
      SkyscannerCode: "PRG",
    },
    {
      IataCode: "PRN",
      city: "Pristina",
      country: "Kosovo",
      SkyscannerCode: "PRN",
    },
    {
      IataCode: "PTP",
      city: "Pointe a Pitre",
      country: "Guadeloupe",
      SkyscannerCode: "PTP",
    },
    {
      IataCode: "PTY",
      city: "Panama City",
      country: "Panama",
      SkyscannerCode: "PTY",
    },
    {
      IataCode: "PUJ",
      city: "Punta Cana",
      country: "Dominican Republic",
      SkyscannerCode: "PUJ",
    },
    {
      IataCode: "RAI",
      city: "Praia",
      country: "Cape Verde",
      SkyscannerCode: "RAI",
    },
    {
      IataCode: "RGN",
      city: "Yangon",
      country: "Myanmar",
      SkyscannerCode: "RGN",
    },
    { IataCode: "RIX", city: "Riga", country: "Latvia", SkyscannerCode: "RIX" },
    {
      IataCode: "SAW",
      city: "Istanbul",
      country: "Turkey",
      SkyscannerCode: "SAW",
    },
    {
      IataCode: "SCL",
      city: "Santiago",
      country: "Chile",
      SkyscannerCode: "SCL",
    },
    {
      IataCode: "SEZ",
      city: "Mahe Island",
      country: "Seychelles",
      SkyscannerCode: "SEZ",
    },
    {
      IataCode: "SIN",
      city: "Singapore",
      country: "Singapore",
      SkyscannerCode: "SIN",
    },
    {
      IataCode: "SJO",
      city: "San Jose",
      country: "Costa Rica",
      SkyscannerCode: "SJO",
    },
    {
      IataCode: "SKG",
      city: "Thessaloniki",
      country: "Greece",
      SkyscannerCode: "SKG",
    },
    {
      IataCode: "SLU",
      city: "Castries",
      country: "Saint Lucia",
      SkyscannerCode: "SLU",
    },
    {
      IataCode: "SOF",
      city: "Sofia",
      country: "Bulgaria",
      SkyscannerCode: "SOF",
    },
    {
      IataCode: "SPU",
      city: "Split",
      country: "Croatia",
      SkyscannerCode: "SPU",
    },
    {
      IataCode: "SSH",
      city: "Sharm El Sheikh",
      country: "Egypt",
      SkyscannerCode: "SSH",
    },
    {
      IataCode: "STN",
      city: "London",
      country: "United Kingdom",
      SkyscannerCode: "STN",
    },
    {
      IataCode: "SVD",
      city: "Kingstown",
      country: "Saint Vincent and the Grenadines",
      SkyscannerCode: "SVD",
    },
    {
      IataCode: "SXM",
      city: "Philipsburg",
      country: "St Maarten",
      SkyscannerCode: "SXM",
    },
    {
      IataCode: "TAS",
      city: "Tashkent",
      country: "Uzbekistan",
      SkyscannerCode: "TAS",
    },
    {
      IataCode: "TBS",
      city: "Tbilisi",
      country: "Georgia",
      SkyscannerCode: "TBS",
    },
    {
      IataCode: "TGD",
      city: "Podgorica",
      country: "Montenegro",
      SkyscannerCode: "TGD",
    },
    {
      IataCode: "TGU",
      city: "Tegucigalpa",
      country: "Honduras",
      SkyscannerCode: "TGU",
    },
    {
      IataCode: "TIA",
      city: "Tirana",
      country: "Albania",
      SkyscannerCode: "TIA",
    },
    {
      IataCode: "TLL",
      city: "Tallinn",
      country: "Estonia",
      SkyscannerCode: "TLL",
    },
    {
      IataCode: "TLS",
      city: "Toulouse",
      country: "France",
      SkyscannerCode: "TLS",
    },
    {
      IataCode: "TLV",
      city: "Tel Aviv",
      country: "Israel",
      SkyscannerCode: "TLV",
    },
    {
      IataCode: "TMS",
      city: "Sao Tome Is",
      country: "Sao Tome and Principe",
      SkyscannerCode: "TMS",
    },
    {
      IataCode: "TNR",
      city: "Antananarivo",
      country: "Madagascar",
      SkyscannerCode: "TNR",
    },
    {
      IataCode: "TPE",
      city: "Taipei",
      country: "Taiwan",
      SkyscannerCode: "TPE",
    },
    { IataCode: "TRF", city: "Oslo", country: "Norway", SkyscannerCode: "TRF" },
    {
      IataCode: "TUN",
      city: "Tunis Carthage",
      country: "Tunisia",
      SkyscannerCode: "TUN",
    },
    {
      IataCode: "TZL",
      city: "Tuzla",
      country: "Bosnia and Herzegovina",
      SkyscannerCode: "TZL",
    },
    {
      IataCode: "UIO",
      city: "Quito",
      country: "Ecuador",
      SkyscannerCode: "UIO",
    },
    {
      IataCode: "ULN",
      city: "Ulaanbaatar",
      country: "Mongolia",
      SkyscannerCode: "ULN",
    },
    {
      IataCode: "VIE",
      city: "Vienna",
      country: "Austria",
      SkyscannerCode: "VIE",
    },
    {
      IataCode: "VKO",
      city: "Moscow",
      country: "Russia",
      SkyscannerCode: "VKO",
    },
    {
      IataCode: "VNO",
      city: "Vilnius",
      country: "Lithuania",
      SkyscannerCode: "VNO",
    },
    {
      IataCode: "VTE",
      city: "Vientiane",
      country: "Laos",
      SkyscannerCode: "VTE",
    },
    {
      IataCode: "VVI",
      city: "Santa Cruz",
      country: "Bolivia",
      SkyscannerCode: "VVI",
    },
    {
      IataCode: "WDH",
      city: "Windhoek",
      country: "Namibia",
      SkyscannerCode: "WDH",
    },
    {
      IataCode: "YYZ",
      city: "Toronto",
      country: "Canada",
      SkyscannerCode: "YYZ",
    },
    {
      IataCode: "ZAD",
      city: "Zadar",
      country: "Croatia",
      SkyscannerCode: "ZAD",
    },
    {
      IataCode: "AGP",
      city: "Malaga",
      country: "Spain",
      SkyscannerCode: "AGP",
    },
    {
      IataCode: "ALA",
      city: "Almaty",
      country: "Kazakhstan",
      SkyscannerCode: "ALA",
    },
    {
      IataCode: "AMS",
      city: "Amsterdam",
      country: "Netherlands",
      SkyscannerCode: "AMS",
    },
    {
      IataCode: "ARN",
      city: "Stockholm",
      country: "Sweden",
      SkyscannerCode: "ARN",
    },
    {
      IataCode: "ASM",
      city: "Asmara",
      country: "Eritrea",
      SkyscannerCode: "ASM",
    },
    {
      IataCode: "BLR",
      city: "Bengaluru",
      country: "India",
      SkyscannerCode: "BLR",
    },
    {
      IataCode: "BOD",
      city: "Bordeaux",
      country: "France",
      SkyscannerCode: "BOD",
    },
    {
      IataCode: "BOG",
      city: "Bogota",
      country: "Colombia",
      SkyscannerCode: "BOG",
    },
    {
      IataCode: "BZE",
      city: "Belize City",
      country: "Belize",
      SkyscannerCode: "BZE",
    },
    { IataCode: "CAI", city: "Cairo", country: "Egypt", SkyscannerCode: "CAI" },
    {
      IataCode: "CDG",
      city: "Paris",
      country: "France",
      SkyscannerCode: "CDG",
    },
    {
      IataCode: "CGK",
      city: "Jakarta",
      country: "Indonesia",
      SkyscannerCode: "CGK",
    },
    {
      IataCode: "CHC",
      city: "Christchurch",
      country: "New Zealand",
      SkyscannerCode: "CHC",
    },
    {
      IataCode: "CUN",
      city: "Cancun",
      country: "Mexico",
      SkyscannerCode: "CUN",
    },
    {
      IataCode: "DEL",
      city: "New Delhi",
      country: "India",
      SkyscannerCode: "DEL",
    },
    {
      IataCode: "DMM",
      city: "Dammam",
      country: "Saudi Arabia",
      SkyscannerCode: "DMM",
    },
    {
      IataCode: "DXB",
      city: "Dubai",
      country: "United Arab Emirates",
      SkyscannerCode: "DXB",
    },
    {
      IataCode: "DYU",
      city: "Dushanbe",
      country: "Tajikistan",
      SkyscannerCode: "DYU",
    },
    {
      IataCode: "FAO",
      city: "Faro",
      country: "Portugal",
      SkyscannerCode: "FAO",
    },
    {
      IataCode: "FRA",
      city: "Frankfurt",
      country: "Germany",
      SkyscannerCode: "FRA",
    },
    {
      IataCode: "GUM",
      city: "Barrigada",
      country: "Guam",
      SkyscannerCode: "GUM",
    },
    {
      IataCode: "HAM",
      city: "Hamburg",
      country: "Germany",
      SkyscannerCode: "HAM",
    },
    { IataCode: "HAV", city: "Havana", country: "Cuba", SkyscannerCode: "HAV" },
    {
      IataCode: "HRG",
      city: "Hurghada",
      country: "Egypt",
      SkyscannerCode: "HRG",
    },
    { IataCode: "KGS", city: "Kos", country: "Greece", SkyscannerCode: "KGS" },
    {
      IataCode: "LAD",
      city: "Luanda",
      country: "Angola",
      SkyscannerCode: "LAD",
    },
    {
      IataCode: "LCA",
      city: "Larnaca",
      country: "Cyprus",
      SkyscannerCode: "LCA",
    },
    {
      IataCode: "LED",
      city: "St Petersburg",
      country: "Russia",
      SkyscannerCode: "LED",
    },
    {
      IataCode: "LHE",
      city: "Lahore",
      country: "Pakistan",
      SkyscannerCode: "LHE",
    },
    {
      IataCode: "LOS",
      city: "Lagos",
      country: "Nigeria",
      SkyscannerCode: "LOS",
    },
    {
      IataCode: "LPB",
      city: "La Paz",
      country: "Bolivia",
      SkyscannerCode: "LPB",
    },
    { IataCode: "NAN", city: "Nadi", country: "Fiji", SkyscannerCode: "NAN" },
    {
      IataCode: "OTP",
      city: "Bucharest",
      country: "Romania",
      SkyscannerCode: "OTP",
    },
    {
      IataCode: "PUY",
      city: "Pula",
      country: "Croatia",
      SkyscannerCode: "PUY",
    },
    {
      IataCode: "RAK",
      city: "Marrakech Menara",
      country: "Morocco",
      SkyscannerCode: "RAK",
    },
    {
      IataCode: "SGN",
      city: "Ho Chi Minh City",
      country: "Vietnam",
      SkyscannerCode: "SGN",
    },
    {
      IataCode: "SIP",
      city: "Simferopol",
      country: "Crimea",
      SkyscannerCode: "SIP",
    },
    {
      IataCode: "SJU",
      city: "San Juan",
      country: "Puerto Rico",
      SkyscannerCode: "SJU",
    },
    {
      IataCode: "SKP",
      city: "Skopje",
      country: "North Macedonia",
      SkyscannerCode: "SKP",
    },
    {
      IataCode: "SZG",
      city: "Salzburg",
      country: "Austria",
      SkyscannerCode: "SZG",
    },
    {
      IataCode: "TIP",
      city: "Tripoli",
      country: "Libya",
      SkyscannerCode: "TIP",
    },
    {
      IataCode: "TXL",
      city: "Berlin",
      country: "Germany",
      SkyscannerCode: "TXL",
    },
    {
      IataCode: "YUL",
      city: "Montreal",
      country: "Canada",
      SkyscannerCode: "YUL",
    },
    {
      IataCode: "ZAG",
      city: "Zagreb",
      country: "Croatia",
      SkyscannerCode: "ZAG",
    },
    {
      IataCode: "ATH",
      city: "Athens",
      country: "Greece",
      SkyscannerCode: "ATH",
    },
    {
      IataCode: "BGF",
      city: "Bangui",
      country: "Central African Republic",
      SkyscannerCode: "BGF",
    },
    {
      IataCode: "BJM",
      city: "Bujumbura",
      country: "Burundi",
      SkyscannerCode: "BJM",
    },
    {
      IataCode: "BZV",
      city: "Brazzaville",
      country: "Republic of the Congo",
      SkyscannerCode: "BZV",
    },
    {
      IataCode: "CKY",
      city: "Conakry",
      country: "Guinea",
      SkyscannerCode: "CKY",
    },
    {
      IataCode: "CPT",
      city: "Cape Town",
      country: "South Africa",
      SkyscannerCode: "CPT",
    },
    {
      IataCode: "DPS",
      city: "Denpasar",
      country: "Indonesia",
      SkyscannerCode: "DPS",
    },
    {
      IataCode: "DZA",
      city: "Dzaoudzi",
      country: "Mayotte",
      SkyscannerCode: "DZA",
    },
    {
      IataCode: "ESB",
      city: "Ankara",
      country: "Turkey",
      SkyscannerCode: "ESB",
    },
    { IataCode: "FCO", city: "Rome", country: "Italy", SkyscannerCode: "FCO" },
    {
      IataCode: "FDF",
      city: "Fort De France",
      country: "Martinique",
      SkyscannerCode: "FDF",
    },
    {
      IataCode: "GDL",
      city: "Guadalajara",
      country: "Mexico",
      SkyscannerCode: "GDL",
    },
    {
      IataCode: "GEO",
      city: "Georgetown",
      country: "Guyana",
      SkyscannerCode: "GEO",
    },
    {
      IataCode: "GIG",
      city: "Rio De Janeiro",
      country: "Brazil",
      SkyscannerCode: "GIG",
    },
    {
      IataCode: "ISB",
      city: "Islamabad",
      country: "Pakistan",
      SkyscannerCode: "ISB",
    },
    {
      IataCode: "KSC",
      city: "Kosice",
      country: "Slovakia",
      SkyscannerCode: "KSC",
    },
    {
      IataCode: "KUT",
      city: "Kutaisi",
      country: "Georgia",
      SkyscannerCode: "KUT",
    },
    {
      IataCode: "LWO",
      city: "Lviv",
      country: "Ukraine",
      SkyscannerCode: "LWO",
    },
    {
      IataCode: "MUC",
      city: "Munich",
      country: "Germany",
      SkyscannerCode: "MUC",
    },
    { IataCode: "NCE", city: "Nice", country: "France", SkyscannerCode: "NCE" },
    {
      IataCode: "NDJ",
      city: "N’Djamena",
      country: "Chad",
      SkyscannerCode: "NDJ",
    },
    {
      IataCode: "NIM",
      city: "Niamey",
      country: "Niger",
      SkyscannerCode: "NIM",
    },
    {
      IataCode: "NKC",
      city: "Nouakchott",
      country: "Mauritania",
      SkyscannerCode: "NKC",
    },
    {
      IataCode: "OPO",
      city: "Porto",
      country: "Portugal",
      SkyscannerCode: "OPO",
    },
    {
      IataCode: "PMO",
      city: "Palermo",
      country: "Italy",
      SkyscannerCode: "PMO",
    },
    {
      IataCode: "PVG",
      city: "Shanghai",
      country: "China",
      SkyscannerCode: "PVG",
    },
    {
      IataCode: "RUN",
      city: "Saint Denis",
      country: "Reunion",
      SkyscannerCode: "RUN",
    },
    {
      IataCode: "SAP",
      city: "San Pedro Sula",
      country: "Honduras",
      SkyscannerCode: "SAP",
    },
    {
      IataCode: "SBH",
      city: "St Barthelemy",
      country: "Saint Barthelemy",
      SkyscannerCode: "SBH",
    },
    {
      IataCode: "SDQ",
      city: "Santo Domingo",
      country: "Dominican Republic",
      SkyscannerCode: "SDQ",
    },
    {
      IataCode: "SHJ",
      city: "Sharjah",
      country: "United Arab Emirates",
      SkyscannerCode: "SHJ",
    },
    {
      IataCode: "TKU",
      city: "Turku",
      country: "Finland",
      SkyscannerCode: "TKU",
    },
    {
      IataCode: "TNG",
      city: "Tangier",
      country: "Morocco",
      SkyscannerCode: "TNG",
    },
    {
      IataCode: "WAW",
      city: "Warsaw",
      country: "Poland",
      SkyscannerCode: "WAW",
    },
    {
      IataCode: "WMI",
      city: "Nowy Dwor Mazowiecki",
      country: "Poland",
      SkyscannerCode: "WMI",
    },
    {
      IataCode: "ZNZ",
      city: "Zanzibar",
      country: "Tanzania",
      SkyscannerCode: "ZNZ",
    },
    {
      IataCode: "ZRH",
      city: "Zurich",
      country: "Switzerland",
      SkyscannerCode: "ZRH",
    },
    {
      IataCode: "ADB",
      city: "Izmir",
      country: "Turkey",
      SkyscannerCode: "ADB",
    },
    {
      IataCode: "AQJ",
      city: "Aqaba",
      country: "Jordan",
      SkyscannerCode: "AQJ",
    },
    {
      IataCode: "ASB",
      city: "Ashgabat",
      country: "Turkmenistan",
      SkyscannerCode: "ASB",
    },
    {
      IataCode: "ASU",
      city: "Asuncion",
      country: "Paraguay",
      SkyscannerCode: "ASU",
    },
    {
      IataCode: "AUA",
      city: "Oranjestad",
      country: "Aruba",
      SkyscannerCode: "AUA",
    },
    {
      IataCode: "BGO",
      city: "Bergen",
      country: "Norway",
      SkyscannerCode: "BGO",
    },
    { IataCode: "BKO", city: "Bamako", country: "Mali", SkyscannerCode: "BKO" },
    {
      IataCode: "BOB",
      city: "Bora Bora",
      country: "French Polynesia",
      SkyscannerCode: "BOB",
    },
    {
      IataCode: "BON",
      city: "Bonaire",
      country: "Caribbean Netherlands",
      SkyscannerCode: "BON",
    },
    {
      IataCode: "BRS",
      city: "Bristol",
      country: "United Kingdom",
      SkyscannerCode: "BRS",
    },
    {
      IataCode: "BSL",
      city: "Basel",
      country: "Switzerland",
      SkyscannerCode: "BSL",
    },
    {
      IataCode: "CAY",
      city: "Cayenne",
      country: "French Guiana",
      SkyscannerCode: "CAY",
    },
    {
      IataCode: "CCP",
      city: "Concepcion",
      country: "Chile",
      SkyscannerCode: "CCP",
    },
    {
      IataCode: "CUR",
      city: "Curacao",
      country: "Curacao",
      SkyscannerCode: "CUR",
    },
    {
      IataCode: "FBM",
      city: "Lubumbashi",
      country: "DR Congo",
      SkyscannerCode: "FBM",
    },
    {
      IataCode: "GDN",
      city: "Gdansk",
      country: "Poland",
      SkyscannerCode: "GDN",
    },
    {
      IataCode: "GUW",
      city: "Atyrau",
      country: "Kazakhstan",
      SkyscannerCode: "GUW",
    },
    { IataCode: "IBZ", city: "Ibiza", country: "Spain", SkyscannerCode: "IBZ" },
    {
      IataCode: "JRO",
      city: "Kilimanjaro",
      country: "Tanzania",
      SkyscannerCode: "JRO",
    },
    {
      IataCode: "LUN",
      city: "Lusaka",
      country: "Zambia",
      SkyscannerCode: "LUN",
    },
    {
      IataCode: "MDE",
      city: "Medellin",
      country: "Colombia",
      SkyscannerCode: "MDE",
    },
    {
      IataCode: "MGA",
      city: "Managua",
      country: "Nicaragua",
      SkyscannerCode: "MGA",
    },
    {
      IataCode: "MGQ",
      city: "Mogadishu",
      country: "Somalia",
      SkyscannerCode: "MGQ",
    },
    {
      IataCode: "NAS",
      city: "Nassau",
      country: "Bahamas",
      SkyscannerCode: "NAS",
    },
    {
      IataCode: "NDR",
      city: "Nador",
      country: "Morocco",
      SkyscannerCode: "NDR",
    },
    {
      IataCode: "PBM",
      city: "Paramaribo",
      country: "Suriname",
      SkyscannerCode: "PBM",
    },
    {
      IataCode: "RUH",
      city: "Riyadh",
      country: "Saudi Arabia",
      SkyscannerCode: "RUH",
    },
    {
      IataCode: "SAL",
      city: "San Salvador",
      country: "El Salvador",
      SkyscannerCode: "SAL",
    },
    {
      IataCode: "SJJ",
      city: "Sarajevo",
      country: "Bosnia and Herzegovina",
      SkyscannerCode: "SJJ",
    },
    {
      IataCode: "TAT",
      city: "Poprad",
      country: "Slovakia",
      SkyscannerCode: "TAT",
    },
    {
      IataCode: "VRN",
      city: "Verona",
      country: "Italy",
      SkyscannerCode: "VRN",
    },
    {
      IataCode: "YYC",
      city: "Calgary",
      country: "Canada",
      SkyscannerCode: "YYC",
    },
    {
      IataCode: "CBB",
      city: "Cochabamba",
      country: "Bolivia",
      SkyscannerCode: "CBB",
    },
    { IataCode: "COK", city: "Kochi", country: "India", SkyscannerCode: "COK" },
    {
      IataCode: "CRA",
      city: "Craiova",
      country: "Romania",
      SkyscannerCode: "CRA",
    },
    {
      IataCode: "GYE",
      city: "Guayaquil",
      country: "Ecuador",
      SkyscannerCode: "GYE",
    },
    {
      IataCode: "IAD",
      city: "Washington",
      country: "United States",
      SkyscannerCode: "IAD",
    },
    {
      IataCode: "MAD",
      city: "Madrid",
      country: "Spain",
      SkyscannerCode: "MAD",
    },
    {
      IataCode: "MIA",
      city: "Miami",
      country: "United States",
      SkyscannerCode: "MIA",
    },
    {
      IataCode: "MRS",
      city: "Marseille",
      country: "France",
      SkyscannerCode: "MRS",
    },
    {
      IataCode: "SSG",
      city: "Malabo",
      country: "Equatorial Guinea",
      SkyscannerCode: "SSG",
    },
    { IataCode: "VGO", city: "Vigo", country: "Spain", SkyscannerCode: "VGO" },
    {
      IataCode: "WRO",
      city: "Wroclaw",
      country: "Poland",
      SkyscannerCode: "WRO",
    },
  ];
};
types = () => {
  let types = [
    {
      city: "Abuja",
      country: "Nigeria",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Accra",
      country: "Ghana",
      main_type: "city",
      secondary_type: "beach",
    },
    {
      city: "Addis Ababa",
      country: "Ethiopia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Auckland",
      country: "New Zealand",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Algiers",
      country: "Algeria",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Amman",
      country: "Jordan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Abu Dhabi",
      country: "United Arab Emirates",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Manama",
      country: "Bahrain",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Barcelona",
      country: "Spain",
      main_type: "culture",
      secondary_type: "beach",
    },
    {
      city: "Belgrade",
      country: "Serbia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Beirut",
      country: "Lebanon",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Bridgetown",
      country: "Barbados",
      main_type: "culture",
      secondary_type: "nightlife",
    },
    {
      city: "Bangkok",
      country: "Thailand",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Brussels",
      country: "Belgium",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Bratislava",
      country: "Slovakia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Budapest",
      country: "Hungary",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Colombo",
      country: "Sri Lanka",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Casablanca",
      country: "Morocco",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Cotonou",
      country: "Benin",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Copenhagen",
      country: "Denmark",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Dhaka",
      country: "Bangladesh",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Dar Es Salaam",
      country: "Tanzania",
      main_type: "city",
      secondary_type: "coast",
    },
    {
      city: "Dalaman",
      country: "Turkey",
      main_type: "nature",
      secondary_type: "empty",
    },
    {
      city: "Doha",
      country: "Qatar",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Dakar",
      country: "Senegal",
      main_type: "nightlife",
      secondary_type: "city",
    },
    {
      city: "Dublin",
      country: "Ireland",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Entebbe",
      country: "Uganda",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Yerevan",
      country: "Armenia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Buenos Aires",
      country: "Argentina",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Freetown",
      country: "Sierra Leone",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Bishkek",
      country: "Kyrgyzstan",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Sao Paulo",
      country: "Brazil",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Guatemala City",
      country: "Guatemala",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Geneva",
      country: "Switzerland",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Hanoi",
      country: "Vietnam",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Helsinki",
      country: "Finland",
      main_type: "ski",
      secondary_type: "culture",
    },
    {
      city: "Harare",
      country: "Zimbabwe",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Seoul",
      country: "South Korea",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Kyiv",
      country: "Ukraine",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Tehran",
      country: "Iran",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Kabul",
      country: "Afghanistan",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Reykjavik",
      country: "Iceland",
      main_type: "culture",
      secondary_type: "food",
    },
    {
      city: "Kigali",
      country: "Rwanda",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Kingston",
      country: "Jamaica",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Chisinau",
      country: "Moldova",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Khartoum",
      country: "Sudan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Kathmandu",
      country: "Nepal",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Kuala Lumpur",
      country: "Malaysia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Libreville",
      country: "Gabon",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Lome",
      country: "Togo",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Lima",
      country: "Peru",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Lisbon",
      country: "Portugal",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Ljubljana",
      country: "Slovenia",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Muscat",
      country: "Oman",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Mexico City",
      country: "Mexico",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Malé",
      country: "Maldives",
      main_type: "city",
      secondary_type: "coast",
    },
    {
      city: "Manila",
      country: "Philippines",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Maputo",
      country: "Mozambique",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Minsk",
      country: "Belarus",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Montevideo",
      country: "Uruguay",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Milan",
      country: "Italy",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Nairobi",
      country: "Kenya",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Tokyo",
      country: "Japan",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Ouagadougou",
      country: "Burkina Faso",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Perth",
      country: "Australia",
      main_type: "coast",
      secondary_type: "beach",
    },
    {
      city: "Phnom Penh",
      country: "Cambodia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Pointe a Pitre",
      country: "Guadeloupe",
      main_type: "culture",
      secondary_type: "coast",
    },
    {
      city: "Panama City",
      country: "Panama",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Riga",
      country: "Latvia",
      main_type: "city",
      secondary_type: "coast",
    },
    {
      city: "Istanbul",
      country: "Turkey",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Santiago",
      country: "Chile",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "San Jose",
      country: "Costa Rica",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Sofia",
      country: "Bulgaria",
      main_type: "city",
      secondary_type: "ski",
    },
    {
      city: "Tashkent",
      country: "Uzbekistan",
      main_type: "ski",
      secondary_type: "city",
    },
    {
      city: "Tbilisi",
      country: "Georgia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Podgorica",
      country: "Montenegro",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Tegucigalpa",
      country: "Honduras",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Tirana",
      country: "Albania",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Tallinn",
      country: "Estonia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Toulouse",
      country: "France",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Antananarivo",
      country: "Madagascar",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Taipei",
      country: "Taiwan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Oslo",
      country: "Norway",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Quito",
      country: "Ecuador",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Ulaanbaatar",
      country: "Mongolia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Vienna",
      country: "Austria",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Moscow",
      country: "Russia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Vilnius",
      country: "Lithuania",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Vientiane",
      country: "Laos",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Windhoek",
      country: "Namibia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Toronto",
      country: "Canada",
      main_type: "nightlife",
      secondary_type: "city",
    },
    {
      city: "Almaty",
      country: "Kazakhstan",
      main_type: "ski",
      secondary_type: "nightlife",
    },
    {
      city: "Stockholm",
      country: "Sweden",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Asmara",
      country: "Eritrea",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Bogota",
      country: "Colombia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Belize City",
      country: "Belize",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Cairo",
      country: "Egypt",
      main_type: "city",
      secondary_type: "empty",
    },
    {
      city: "Paris",
      country: "France",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Jakarta",
      country: "Indonesia",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Cancun",
      country: "Mexico",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Dammam",
      country: "Saudi Arabia",
      main_type: "food",
      secondary_type: "city",
    },
    {
      city: "Dubai",
      country: "United Arab Emirates",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Dushanbe",
      country: "Tajikistan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Hamburg",
      country: "Germany",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Havana",
      country: "Cuba",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "St Petersburg",
      country: "Russia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Lagos",
      country: "Nigeria",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "La Paz",
      country: "Bolivia",
      main_type: "city",
      secondary_type: "hot",
    },
    {
      city: "Bucharest",
      country: "Romania",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Ho Chi Minh City",
      country: "Vietnam",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "San Juan",
      country: "Puerto Rico",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Salzburg",
      country: "Austria",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Berlin",
      country: "Germany",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Montreal",
      country: "Canada",
      main_type: "food",
      secondary_type: "city",
    },
    {
      city: "Zagreb",
      country: "Croatia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Athens",
      country: "Greece",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Bujumbura",
      country: "Burundi",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Conakry",
      country: "Guinea",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Cape Town",
      country: "South Africa",
      main_type: "nature",
      secondary_type: "city",
    },
    {
      city: "Rome",
      country: "Italy",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Fort De France",
      country: "Martinique",
      main_type: "city",
      secondary_type: "beach",
    },
    {
      city: "Rio De Janeiro",
      country: "Brazil",
      main_type: "beach",
      secondary_type: "nature",
    },
    {
      city: "Munich",
      country: "Germany",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Nice",
      country: "France",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Nouakchott",
      country: "Mauritania",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Shanghai",
      country: "China",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Santo Domingo",
      country: "Dominican Republic",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Warsaw",
      country: "Poland",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Zurich",
      country: "Switzerland",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Ashgabat",
      country: "Turkmenistan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Asuncion",
      country: "Paraguay",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Oranjestad",
      country: "Aruba",
      main_type: "city",
      secondary_type: "beach",
    },
    {
      city: "Ibiza",
      country: "Spain",
      main_type: "beach",
      secondary_type: "nightlife",
    },
    {
      city: "Lusaka",
      country: "Zambia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Managua",
      country: "Nicaragua",
      main_type: "culture",
      secondary_type: "beach",
    },
    {
      city: "Nador",
      country: "Morocco",
      main_type: "coast",
      secondary_type: "food",
    },
    {
      city: "Riyadh",
      country: "Saudi Arabia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "San Salvador",
      country: "El Salvador",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Craiova",
      country: "Romania",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Madrid",
      country: "Spain",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Malabo",
      country: "Equatorial Guinea",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Vigo",
      country: "Spain",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Abidjan",
      country: "Ivory Coast",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Saint John’s",
      country: "Antigua and Barbuda",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Hamilton",
      country: "Bermuda",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Banjul",
      country: "Gambia",
      main_type: "nature",
      secondary_type: "beach",
    },
    {
      city: "Blantyre",
      country: "Malawi",
      main_type: "food",
      secondary_type: "city",
    },
    {
      city: "Mumbai",
      country: "India",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Bandar Seri Begawan",
      country: "Brunei",
      main_type: "city",
      secondary_type: "beach",
    },
    {
      city: "Corfu",
      country: "Greece",
      main_type: "coast",
      secondary_type: "beach",
    },
    {
      city: "Cologne",
      country: "Germany",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Cluj Napoca",
      country: "Romania",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Cali",
      country: "Colombia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Chengdu",
      country: "China",
      main_type: "culture",
      secondary_type: "nightlife",
    },
    {
      city: "Douala",
      country: "Cameroon",
      main_type: "city",
      secondary_type: "coast",
    },
    {
      city: "Dominica",
      country: "Dominica",
      main_type: "coast",
      secondary_type: "nature",
    },
    {
      city: "Erbil",
      country: "Iraq",
      main_type: "nature",
      secondary_type: "city",
    },
    {
      city: "Edinburgh",
      country: "United Kingdom",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Eindhoven",
      country: "Netherlands",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "New York",
      country: "United States",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Sorvagur",
      country: "Faroe Islands",
      main_type: "coast",
      secondary_type: "nature",
    },
    {
      city: "Kinshasa",
      country: "DR Congo",
      main_type: "culture",
      secondary_type: "empty",
    },
    {
      city: "Guernsey",
      country: "Guernsey",
      main_type: "coast",
      secondary_type: "beach",
    },
    {
      city: "Gibraltar",
      country: "Gibraltar",
      main_type: "culture",
      secondary_type: "beach",
    },
    {
      city: "St. George",
      country: "Grenada",
      main_type: "coast",
      secondary_type: "beach",
    },
    {
      city: "Nuuk",
      country: "Greenland",
      main_type: "ski",
      secondary_type: "culture",
    },
    {
      city: "Gothenburg",
      country: "Sweden",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Baku",
      country: "Azerbaijan",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Hargeisa",
      country: "Somalia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Hong Kong",
      country: "Hong Kong",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Jeddah",
      country: "Saudi Arabia",
      main_type: "culture",
      secondary_type: "coast",
    },
    {
      city: "Djibouti",
      country: "Djibouti",
      main_type: "nature",
      secondary_type: "beach",
    },
    {
      city: "Johannesburg",
      country: "South Africa",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Medan",
      country: "Indonesia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Krakow",
      country: "Poland",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Kuwait",
      country: "Kuwait",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Luxembourg",
      country: "Luxembourg",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Macau",
      country: "Macau",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Luqa",
      country: "Malta",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Mauritius",
      country: "Mauritius",
      main_type: "beach",
      secondary_type: "nature",
    },
    {
      city: "Nur Sultan",
      country: "Kazakhstan",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Ohrid",
      country: "North Macedonia",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Providenciales",
      country: "Turks and Caicos Islands",
      main_type: "beach",
      secondary_type: "nightlife",
    },
    {
      city: "Port Of Spain",
      country: "Trinidad and Tobago",
      main_type: "coast",
      secondary_type: "nightlife",
    },
    {
      city: "Papeete",
      country: "French Polynesia",
      main_type: "beach",
      secondary_type: "culture",
    },
    {
      city: "Prague",
      country: "Czechia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Pristina",
      country: "Kosovo",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Punta Cana",
      country: "Dominican Republic",
      main_type: "beach",
      secondary_type: "empty",
    },
    {
      city: "Praia",
      country: "Cape Verde",
      main_type: "beach",
      secondary_type: "nightlife",
    },
    {
      city: "Yangon",
      country: "Myanmar",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Mahe Island",
      country: "Seychelles",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Singapore",
      country: "Singapore",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Thessaloniki",
      country: "Greece",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Castries",
      country: "Saint Lucia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Sharm El Sheikh",
      country: "Egypt",
      main_type: "coast",
      secondary_type: "beach",
    },
    {
      city: "London",
      country: "United Kingdom",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Kingstown",
      country: "Saint Vincent and the Grenadines",
      main_type: "beach",
      secondary_type: "nature",
    },
    {
      city: "Philipsburg",
      country: "St Maarten",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Tel Aviv",
      country: "Israel",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Sao Tome Is",
      country: "Sao Tome and Principe",
      main_type: "coast",
      secondary_type: "culture",
    },
    {
      city: "Tunis Carthage",
      country: "Tunisia",
      main_type: "empty",
      secondary_type: "empty",
    },
    {
      city: "Tuzla",
      country: "Bosnia and Herzegovina",
      main_type: "ski",
      secondary_type: "culture",
    },
    {
      city: "Santa Cruz",
      country: "Bolivia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Zadar",
      country: "Croatia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Malaga",
      country: "Spain",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Amsterdam",
      country: "Netherlands",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Bengaluru",
      country: "India",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Bordeaux",
      country: "France",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Christchurch",
      country: "New Zealand",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "New Delhi",
      country: "India",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Faro",
      country: "Portugal",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Frankfurt",
      country: "Germany",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Hurghada",
      country: "Egypt",
      main_type: "culture",
      secondary_type: "empty",
    },
    {
      city: "Kos",
      country: "Greece",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Larnaca",
      country: "Cyprus",
      main_type: "beach",
      secondary_type: "food",
    },
    {
      city: "Nadi",
      country: "Fiji",
      main_type: "culture",
      secondary_type: "coast",
    },
    {
      city: "Pula",
      country: "Croatia",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Simferopol",
      country: "Crimea",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Skopje",
      country: "North Macedonia",
      main_type: "culture",
      secondary_type: "nature",
    },
    {
      city: "Tripoli",
      country: "Libya",
      main_type: "nature",
      secondary_type: "culture",
    },
    {
      city: "Bangui",
      country: "Central African Republic",
      main_type: "nature",
      secondary_type: "empty",
    },
    {
      city: "Brazzaville",
      country: "Republic of the Congo",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Denpasar",
      country: "Indonesia",
      main_type: "coast",
      secondary_type: "food",
    },
    {
      city: "Ankara",
      country: "Turkey",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Guadalajara",
      country: "Mexico",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Georgetown",
      country: "Guyana",
      main_type: "nature",
      secondary_type: "city",
    },
    {
      city: "Kosice",
      country: "Slovakia",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Kutaisi",
      country: "Georgia",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Lviv",
      country: "Ukraine",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Porto",
      country: "Portugal",
      main_type: "city",
      secondary_type: "coast",
    },
    {
      city: "Palermo",
      country: "Italy",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Saint Denis",
      country: "Reunion",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "San Pedro Sula",
      country: "Honduras",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "St Barthelemy",
      country: "Saint Barthelemy",
      main_type: "beach",
      secondary_type: "hot",
    },
    {
      city: "Sharjah",
      country: "United Arab Emirates",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Turku",
      country: "Finland",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Tangier",
      country: "Morocco",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Izmir",
      country: "Turkey",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Aqaba",
      country: "Jordan",
      main_type: "nightlife",
      secondary_type: "coast",
    },
    {
      city: "Bergen",
      country: "Norway",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Bora Bora",
      country: "French Polynesia",
      main_type: "nightlife",
      secondary_type: "nature",
    },
    {
      city: "Bonaire",
      country: "Caribbean Netherlands",
      main_type: "coast",
      secondary_type: "culture",
    },
    {
      city: "Bristol",
      country: "United Kingdom",
      main_type: "food",
      secondary_type: "culture",
    },
    {
      city: "Basel",
      country: "Switzerland",
      main_type: "culture",
      secondary_type: "city",
    },
    {
      city: "Cayenne",
      country: "French Guiana",
      main_type: "culture",
      secondary_type: "empty",
    },
    {
      city: "Concepcion",
      country: "Chile",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Curacao",
      country: "Curacao",
      main_type: "culture",
      secondary_type: "beach",
    },
    {
      city: "Lubumbashi",
      country: "DR Congo",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Gdansk",
      country: "Poland",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Atyrau",
      country: "Kazakhstan",
      main_type: "culture",
      secondary_type: "nature",
    },
    {
      city: "Kilimanjaro",
      country: "Tanzania",
      main_type: "nature",
      secondary_type: "culture",
    },
    {
      city: "Medellin",
      country: "Colombia",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Mogadishu",
      country: "Somalia",
      main_type: "nature",
      secondary_type: "city",
    },
    {
      city: "Nassau",
      country: "Bahamas",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Paramaribo",
      country: "Suriname",
      main_type: "nature",
      secondary_type: "culture",
    },
    {
      city: "Sarajevo",
      country: "Bosnia and Herzegovina",
      main_type: "ski",
      secondary_type: "culture",
    },
    {
      city: "Poprad",
      country: "Slovakia",
      main_type: "ski",
      secondary_type: "city",
    },
    {
      city: "Verona",
      country: "Italy",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Calgary",
      country: "Canada",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Cochabamba",
      country: "Bolivia",
      main_type: "city",
      secondary_type: "food",
    },
    {
      city: "Kochi",
      country: "India",
      main_type: "culture",
      secondary_type: "coast",
    },
    {
      city: "Guayaquil",
      country: "Ecuador",
      main_type: "city",
      secondary_type: "nightlife",
    },
    {
      city: "Washington",
      country: "United States",
      main_type: "city",
      secondary_type: "nature",
    },
    {
      city: "Miami",
      country: "United States",
      main_type: "beach",
      secondary_type: "city",
    },
    {
      city: "Marseille",
      country: "France",
      main_type: "city",
      secondary_type: "culture",
    },
    {
      city: "Wroclaw",
      country: "Poland",
      main_type: "city",
      secondary_type: "culture",
    },
  ];
  return types;
};

// Checks all includes

// let old_list = defineCityTypes();
// let new_list = defineUniqueCities();
// let failed = (success = 0);
// old_list.forEach((old_location) => {
//   if (
//     !new_list.some((new_location) => new_location.city === old_location.city)
//   ) {
//     failed++;
//     console.log(old_location.city + " Not included");
//   } else {
//     success++;
//     console.log(old_location.city + " included");
//   }
// });
// console.log("success" + success, "failed" + failed);
